### ISSUE TITLE
Get "TypeError: Invalid character in header content ["Content-Disposition"]" when handling an UTF8 named file

### ISSUE THREAD

**Issue by VishnuSanyal** [mjackson/remix-the-web#30]
When I use Remix `action` to process a file uploaded by a client that contains non-ASCII characters for naming, I get the error: 

```
TypeError: Invalid character in header content ["Content-Disposition"]
    at Proxy.<anonymous> ([PROJECTDIR]\node_modules\.pnpm\@remix-run+web-fetch@4.4.2\node_modules\@remix-run\web-fetch\src\headers.js:121:8)
    at new _SuperHeaders ([PROJECTDIR]/node_modules/.pnpm/@mjackson+headers@0.8.0/node_modules/@mjackson/headers/dist/headers.js:621:18)
    at MultipartPart.get headers [as headers] ([PROJECTDIR]/node_modules/.pnpm/@mjackson+multipart-parser@0.7.0/node_modules/@mjackson/multipart-parser/dist/multipart-parser.js:348:23)
    at MultipartPart.get name [as name] ([PROJECTDIR]/node_modules/.pnpm/@mjackson+multipart-parser@0.7.0/node_modules/@mjackson/multipart-parser/dist/multipart-parser.js:374:17)
    at parseFormData ([PROJECTDIR]/node_modules/.pnpm/@mjackson+form-data-parser@0.5.0/node_modules/@mjackson/form-data-parser/dist/form-data-parser.js:51:17)    
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at action$5 ([PROJECTDIR]/build/server/index.js?t=1732423388940.4094:7422:5)
    at Object.callRouteAction ([PROJECTDIR]\node_modules\.pnpm\@remix-run+server-runtime@2.15.0_typescript@5.7.2\node_modules\@remix-run\server-runtime\dist\data.js:36:16)
    at [PROJECTDIR]\node_modules\.pnpm\@remix-run+router@1.21.0\node_modules\@remix-run\router\router.ts:4899:19
    at callLoaderOrAction ([PROJECTDIR]\node_modules\.pnpm\@remix-run+router@1.21.0\node_modules\@remix-run\router\router.ts:4963:16) {
  code: 'ERR_INVALID_CHAR'
}
```

**Comment by mjackson** [comment]
Interesting. Any interest in providing a failing test case? I'd be happy to take a look.

**Comment by wong2** [comment]
Same here. This error shows up when I upload a file with a Chinese name.

**Comment by wong2** [comment]
I think the problem is, why it is still using the headers from `@remix-run/web-fetch` instead of the built-in Node.js ones, even after enabling `v3_singleFetch`?

**Comment by mjackson** [comment]
I'm going to assume this issue is due to using the broken `Headers` class we shipped with Remix instead of the standard `Headers` class that ships with Node.js (undici). Just stop using our polyfill and use the class built in to Node and you should be fine.

**Comment by mjackson** [comment]
If you're still on Remix v2 you can opt out of our polyfill using:

```ts
installGlobals({ nativeFetch: true })
```
